using System;
using System.Collections.Generic;
using Avalonia.Media;

namespace Client.Services;

public static class ThemeColors
{
    public static IReadOnlyDictionary<string, Color> BuildCustom(CustomThemeAnchors anchors)
    {
        var bg = anchors.Background;
        var surf = anchors.Surface;
        var border = anchors.Border;
        var accent = anchors.Accent;
        var text = anchors.TextPrimary;

        var isDark = RelativeLuminance(bg) < 0.5;

        var textSecondary = Lerp(text, bg, 0.55);
        var accentHover = Lerp(accent, bg, 0.18);
        var accentPressed = Lerp(accent, bg, 0.36);
        var accentForeground = RelativeLuminance(accent) > 0.55 ? bg : Color.FromRgb(0xFF, 0xFF, 0xFF);
        var systemAccentDark1 = Lerp(accent, bg, 0.12);
        var systemAccentDark2 = Lerp(accent, bg, 0.24);
        var systemAccentDark3 = Lerp(accent, bg, 0.38);
        var systemAccentLight1 = Lerp(accent, text, 0.18);
        var systemAccentLight2 = Lerp(accent, text, 0.32);
        var systemAccentLight3 = Lerp(accent, text, 0.48);

        var inputHoverSurface = Lerp(surf, border, 0.35);
        var inputHoverBorder = Lerp(border, text, 0.25);
        var inputFocusSurface = Lerp(surf, bg, 0.5);
        var inputFocusBorder = accentHover;

        var tableSurface = Lerp(surf, bg, 0.4);
        var tableHeaderBackground = Lerp(surf, border, 0.2);

        var sidebarHoverBackground = Lerp(bg, border, 0.35);
        var sidebarSelectedBackground = Lerp(bg, border, 0.6);

        var updateBannerBackground = Lerp(bg, accent, 0.18);
        var shellShadow = isDark ? Color.FromArgb(0x40, 0x00, 0x00, 0x00) : Color.FromArgb(0x16, text.R, text.G, text.B);
        var shellSelectedShadow = isDark ? Color.FromArgb(0x60, 0x00, 0x00, 0x00) : Color.FromArgb(0x20, text.R, text.G, text.B);

        return new Dictionary<string, Color>
        {
            ["Background"]               = bg,
            ["Surface"]                  = surf,
            ["Border"]                   = border,
            ["Accent"]                   = accent,
            ["AccentHover"]              = accentHover,
            ["AccentPressed"]            = accentPressed,
            ["AccentForeground"]         = accentForeground,
            ["SystemAccentColor"]        = accent,
            ["SystemAccentColorDark1"]   = systemAccentDark1,
            ["SystemAccentColorDark2"]   = systemAccentDark2,
            ["SystemAccentColorDark3"]   = systemAccentDark3,
            ["SystemAccentColorLight1"]  = systemAccentLight1,
            ["SystemAccentColorLight2"]  = systemAccentLight2,
            ["SystemAccentColorLight3"]  = systemAccentLight3,
            ["ThemeAccentColor"]         = accent,
            ["ThemeAccentBrush3"]        = systemAccentLight1,
            ["ThemeAccentBrush4"]        = systemAccentLight2,
            ["SystemControlHighlightListAccentLowBrush"] = systemAccentDark2,
            ["TextPrimary"]              = text,
            ["TextSecondary"]            = textSecondary,
            ["PlaceholderForeground"]    = Lerp(text, bg, 0.38),
            ["Success"]                  = isDark ? Color.Parse("#4ADE80") : Color.Parse("#15803D"),
            ["Error"]                    = isDark ? Color.Parse("#F87171") : Color.Parse("#DC2626"),
            ["InputHoverSurface"]        = inputHoverSurface,
            ["InputHoverBorder"]         = inputHoverBorder,
            ["InputFocusSurface"]        = inputFocusSurface,
            ["InputFocusBorder"]         = inputFocusBorder,
            ["TableSurface"]             = tableSurface,
            ["TableRowBackground"]       = tableSurface,
            ["TableGap"]                 = bg,
            ["TableHeaderBackground"]    = tableHeaderBackground,
            ["TableEmptyBackground"]     = tableSurface,
            ["TableRowDisabled"]         = tableSurface,
            ["SidebarItemForeground"]             = textSecondary,
            ["SidebarItemHoverForeground"]        = text,
            ["SidebarItemHoverBackground"]        = sidebarHoverBackground,
            ["SidebarItemSelectedForeground"]     = text,
            ["SidebarItemSelectedBackground"]     = sidebarSelectedBackground,
            ["ButtonSecondaryBackground"]         = Color.FromArgb(0, 0, 0, 0),
            ["ButtonSecondaryForeground"]         = text,
            ["ButtonSecondaryBorder"]             = border,
            ["ButtonSecondaryHoverBackground"]    = inputHoverSurface,
            ["ButtonSecondaryHoverBorder"]        = inputHoverBorder,
            ["ButtonSecondaryPressedBackground"]  = inputFocusSurface,
            ["CheckboxBackground"]                = surf,
            ["CheckboxBorder"]                    = textSecondary,
            ["CheckboxHoverBackground"]           = inputHoverSurface,
            ["CheckboxHoverBorder"]               = accent,
            ["CheckboxCheckedBackground"]         = accent,
            ["CheckboxCheckedBorder"]             = accent,
            ["CheckboxCheckForeground"]           = accentForeground,
            ["CheckboxLabelForeground"]           = text,
            ["CheckboxLabelHoverForeground"]      = text,
            ["RobloxBannerBackground"]            = updateBannerBackground,
            ["ThemeCardHoverBackground"]          = inputHoverSurface,
            ["ToggleHoverBackground"]             = inputHoverSurface,
            ["ToggleHoverBorder"]                 = inputHoverBorder,
            ["ToggleCheckedBackground"]           = sidebarSelectedBackground,
            ["ToggleCheckedBorder"]               = accentPressed,
            ["ShellBackground"]                   = bg,
            ["ShellOuterBorder"]                  = accent,
            ["ShellInnerBorder"]                  = accentHover,
            ["ShellContentBackground"]            = tableSurface,
            ["ShellContentBorder"]                = accent,
            ["ShellNavBackground"]                = surf,
            ["ShellNavHoverBackground"]           = sidebarHoverBackground,
            ["ShellNavHoverBorder"]               = inputHoverBorder,
            ["ShellNavSelectedBackground"]        = sidebarSelectedBackground,
            ["ShellNavSelectedBorder"]            = accent,
            ["ShellNavGlow"]                      = accent,
            ["ShellChromeBackground"]             = tableSurface,
            ["ShellChromeBorder"]                 = border,
            ["ShellShadow"]                       = shellShadow,
            ["ShellSelectedShadow"]               = shellSelectedShadow,
        };
    }

    private static Color Lerp(Color a, Color b, double t)
    {
        t = Math.Clamp(t, 0.0, 1.0);
        return Color.FromArgb(
            (byte)Math.Round(a.A + (b.A - a.A) * t),
            (byte)Math.Round(a.R + (b.R - a.R) * t),
            (byte)Math.Round(a.G + (b.G - a.G) * t),
            (byte)Math.Round(a.B + (b.B - a.B) * t));
    }

    private static double RelativeLuminance(Color c)
        => (0.2126 * c.R + 0.7152 * c.G + 0.0722 * c.B) / 255.0;


    public static IReadOnlyDictionary<string, Color> Dark { get; } = new Dictionary<string, Color>
    {
        ["Background"]               = Color.Parse("#08090B"),
        ["Surface"]                  = Color.Parse("#131519"),
        ["Border"]                   = Color.Parse("#5F646C"),
        ["Accent"]                   = Color.Parse("#E7E9EC"),
        ["AccentHover"]              = Color.Parse("#FFFFFF"),
        ["AccentPressed"]            = Color.Parse("#BFC3C9"),
        ["AccentForeground"]         = Color.Parse("#090A0C"),
        ["SystemAccentColor"]        = Color.Parse("#E7E9EC"),
        ["SystemAccentColorDark1"]   = Color.Parse("#D6D8DC"),
        ["SystemAccentColorDark2"]   = Color.Parse("#BFC3C9"),
        ["SystemAccentColorDark3"]   = Color.Parse("#A4A8B0"),
        ["SystemAccentColorLight1"]  = Color.Parse("#F1F3F5"),
        ["SystemAccentColorLight2"]  = Color.Parse("#F8F9FA"),
        ["SystemAccentColorLight3"]  = Color.Parse("#FFFFFF"),
        ["ThemeAccentColor"]         = Color.Parse("#E7E9EC"),
        ["ThemeAccentBrush3"]        = Color.Parse("#F1F3F5"),
        ["ThemeAccentBrush4"]        = Color.Parse("#F8F9FA"),
        ["SystemControlHighlightListAccentLowBrush"] = Color.Parse("#BFC3C9"),
        ["TextPrimary"]              = Color.Parse("#F5F5F6"),
        ["TextSecondary"]            = Color.Parse("#A7AAB0"),
        ["PlaceholderForeground"]    = Color.Parse("#7C838B"),
        ["Success"]                  = Color.Parse("#4ADE80"),
        ["Error"]                    = Color.Parse("#F87171"),
        ["InputHoverSurface"]        = Color.Parse("#202329"),
        ["InputHoverBorder"]         = Color.Parse("#8D929A"),
        ["InputFocusSurface"]        = Color.Parse("#181B20"),
        ["InputFocusBorder"]         = Color.Parse("#F1F2F4"),
        ["TableSurface"]             = Color.Parse("#101216"),
        ["TableRowBackground"]       = Color.Parse("#101216"),
        ["TableGap"]                 = Color.Parse("#08090B"),
        ["TableHeaderBackground"]    = Color.Parse("#1A1D22"),
        ["TableEmptyBackground"]     = Color.Parse("#101216"),
        ["TableRowDisabled"]         = Color.Parse("#101216"),
        ["SidebarItemForeground"]             = Color.Parse("#A7AAB0"),
        ["SidebarItemHoverForeground"]        = Color.Parse("#F5F5F6"),
        ["SidebarItemHoverBackground"]        = Color.Parse("#202329"),
        ["SidebarItemSelectedForeground"]     = Color.Parse("#FFFFFF"),
        ["SidebarItemSelectedBackground"]     = Color.Parse("#4B4F56"),
        ["ButtonSecondaryBackground"]         = Color.Parse("#00000000"),
        ["ButtonSecondaryForeground"]         = Color.Parse("#E7E9EC"),
        ["ButtonSecondaryBorder"]             = Color.Parse("#777C84"),
        ["ButtonSecondaryHoverBackground"]    = Color.Parse("#202329"),
        ["ButtonSecondaryHoverBorder"]        = Color.Parse("#F1F2F4"),
        ["ButtonSecondaryPressedBackground"]  = Color.Parse("#191C21"),
        ["CheckboxBackground"]                = Color.Parse("#131519"),
        ["CheckboxBorder"]                    = Color.Parse("#92969D"),
        ["CheckboxHoverBackground"]           = Color.Parse("#202329"),
        ["CheckboxHoverBorder"]               = Color.Parse("#F1F2F4"),
        ["CheckboxCheckedBackground"]         = Color.Parse("#F1F2F4"),
        ["CheckboxCheckedBorder"]             = Color.Parse("#F1F2F4"),
        ["CheckboxCheckForeground"]           = Color.Parse("#090A0C"),
        ["CheckboxLabelForeground"]           = Color.Parse("#F5F5F6"),
        ["CheckboxLabelHoverForeground"]      = Color.Parse("#F5F5F6"),
        ["RobloxBannerBackground"]            = Color.Parse("#131519"),
        ["ThemeCardHoverBackground"]          = Color.Parse("#202329"),
        ["ToggleHoverBackground"]             = Color.Parse("#202329"),
        ["ToggleHoverBorder"]                 = Color.Parse("#777C84"),
        ["ToggleCheckedBackground"]           = Color.Parse("#30343A"),
        ["ToggleCheckedBorder"]               = Color.Parse("#C6C9CE"),
        ["ShellBackground"]                   = Color.Parse("#0C1016"),
        ["ShellOuterBorder"]                  = Color.Parse("#E7E9EC"),
        ["ShellInnerBorder"]                  = Color.Parse("#FFFFFF"),
        ["ShellContentBackground"]            = Color.Parse("#090D13"),
        ["ShellContentBorder"]                = Color.Parse("#E7E9EC"),
        ["ShellNavBackground"]                = Color.Parse("#0B1017"),
        ["ShellNavHoverBackground"]           = Color.Parse("#151B23"),
        ["ShellNavHoverBorder"]               = Color.Parse("#6D7581"),
        ["ShellNavSelectedBackground"]        = Color.Parse("#283341"),
        ["ShellNavSelectedBorder"]            = Color.Parse("#F5F8FC"),
        ["ShellNavGlow"]                      = Color.Parse("#D8E3F0"),
        ["ShellChromeBackground"]             = Color.Parse("#0D0F12"),
        ["ShellChromeBorder"]                 = Color.Parse("#373B42"),
        ["ShellShadow"]                       = Color.Parse("#40000000"),
        ["ShellSelectedShadow"]               = Color.Parse("#60000000"),
    };

    public static IReadOnlyDictionary<string, Color> Light { get; } = new Dictionary<string, Color>
    {
        ["Background"]               = Color.Parse("#F3F7FB"),
        ["Surface"]                  = Color.Parse("#FFFFFF"),
        ["Border"]                   = Color.Parse("#CAD8E6"),
        ["Accent"]                   = Color.Parse("#AFC7DF"),
        ["AccentHover"]              = Color.Parse("#9CB8D4"),
        ["AccentPressed"]            = Color.Parse("#879FB7"),
        ["AccentForeground"]         = Color.Parse("#102030"),
        ["SystemAccentColor"]        = Color.Parse("#AFC7DF"),
        ["SystemAccentColorDark1"]   = Color.Parse("#9CB8D4"),
        ["SystemAccentColorDark2"]   = Color.Parse("#879FB7"),
        ["SystemAccentColorDark3"]   = Color.Parse("#6F889F"),
        ["SystemAccentColorLight1"]  = Color.Parse("#C0D4E7"),
        ["SystemAccentColorLight2"]  = Color.Parse("#D0E0EE"),
        ["SystemAccentColorLight3"]  = Color.Parse("#DFEBF4"),
        ["ThemeAccentColor"]         = Color.Parse("#AFC7DF"),
        ["ThemeAccentBrush3"]        = Color.Parse("#C0D4E7"),
        ["ThemeAccentBrush4"]        = Color.Parse("#D0E0EE"),
        ["SystemControlHighlightListAccentLowBrush"] = Color.Parse("#879FB7"),
        ["TextPrimary"]              = Color.Parse("#182431"),
        ["TextSecondary"]            = Color.Parse("#5E748A"),
        ["PlaceholderForeground"]    = Color.Parse("#6D8297"),
        ["Success"]                  = Color.Parse("#15803D"),
        ["Error"]                    = Color.Parse("#DC2626"),
        ["InputHoverSurface"]        = Color.Parse("#F5F8FC"),
        ["InputHoverBorder"]         = Color.Parse("#B7CAE0"),
        ["InputFocusSurface"]        = Color.Parse("#FFFFFF"),
        ["InputFocusBorder"]         = Color.Parse("#83A9CF"),
        ["TableSurface"]             = Color.Parse("#FDFEFF"),
        ["TableRowBackground"]       = Color.Parse("#FFFFFF"),
        ["TableGap"]                 = Color.Parse("#E8EFF6"),
        ["TableHeaderBackground"]    = Color.Parse("#F2F6FA"),
        ["TableEmptyBackground"]     = Color.Parse("#FFFFFF"),
        ["TableRowDisabled"]         = Color.Parse("#F3F6F9"),
        ["SidebarItemForeground"]             = Color.Parse("#5E748A"),
        ["SidebarItemHoverForeground"]        = Color.Parse("#182431"),
        ["SidebarItemHoverBackground"]        = Color.Parse("#EBF3FA"),
        ["SidebarItemSelectedForeground"]     = Color.Parse("#182431"),
        ["SidebarItemSelectedBackground"]     = Color.Parse("#DCE7F2"),
        ["ButtonSecondaryBackground"]         = Color.Parse("#00000000"),
        ["ButtonSecondaryForeground"]         = Color.Parse("#182431"),
        ["ButtonSecondaryBorder"]             = Color.Parse("#CAD8E6"),
        ["ButtonSecondaryHoverBackground"]    = Color.Parse("#F2F7FC"),
        ["ButtonSecondaryHoverBorder"]        = Color.Parse("#B7CAE0"),
        ["ButtonSecondaryPressedBackground"]  = Color.Parse("#E5EEF7"),
        ["CheckboxBackground"]                = Color.Parse("#FFFFFF"),
        ["CheckboxBorder"]                    = Color.Parse("#93ABC2"),
        ["CheckboxHoverBackground"]           = Color.Parse("#F2F7FC"),
        ["CheckboxHoverBorder"]               = Color.Parse("#83A9CF"),
        ["CheckboxCheckedBackground"]         = Color.Parse("#AFC7DF"),
        ["CheckboxCheckedBorder"]             = Color.Parse("#AFC7DF"),
        ["CheckboxCheckForeground"]           = Color.Parse("#102030"),
        ["CheckboxLabelForeground"]           = Color.Parse("#182431"),
        ["CheckboxLabelHoverForeground"]      = Color.Parse("#182431"),
        ["RobloxBannerBackground"]            = Color.Parse("#E8F3FB"),
        ["ThemeCardHoverBackground"]          = Color.Parse("#F2F7FC"),
        ["ToggleHoverBackground"]             = Color.Parse("#EEF4FA"),
        ["ToggleHoverBorder"]                 = Color.Parse("#B7CAE0"),
        ["ToggleCheckedBackground"]           = Color.Parse("#DCE8F4"),
        ["ToggleCheckedBorder"]               = Color.Parse("#8BAED1"),
        ["ShellBackground"]                   = Color.Parse("#EEF4FA"),
        ["ShellOuterBorder"]                  = Color.Parse("#8FAFCC"),
        ["ShellInnerBorder"]                  = Color.Parse("#C6D7E7"),
        ["ShellContentBackground"]            = Color.Parse("#FFFFFF"),
        ["ShellContentBorder"]                = Color.Parse("#C7D7E7"),
        ["ShellNavBackground"]                = Color.Parse("#FAFCFE"),
        ["ShellNavHoverBackground"]           = Color.Parse("#EEF4FB"),
        ["ShellNavHoverBorder"]               = Color.Parse("#B4CAE0"),
        ["ShellNavSelectedBackground"]        = Color.Parse("#D8E8F8"),
        ["ShellNavSelectedBorder"]            = Color.Parse("#89AFD5"),
        ["ShellNavGlow"]                      = Color.Parse("#D4E6F7"),
        ["ShellChromeBackground"]             = Color.Parse("#F8FBFD"),
        ["ShellChromeBorder"]                 = Color.Parse("#CDD9E5"),
        ["ShellShadow"]                       = Color.Parse("#16182431"),
        ["ShellSelectedShadow"]               = Color.Parse("#24182431"),
    };

    // Soft-pink dark palette. Keeps the same readable dark base as Dark/Slate;
    // accents and selection/hover tints are pink instead of teal.
    public static IReadOnlyDictionary<string, Color> Pink { get; } = new Dictionary<string, Color>
    {
        ["Background"]               = Color.Parse("#161013"),
        ["Surface"]                  = Color.Parse("#1F1719"),
        ["Border"]                   = Color.Parse("#3A2A30"),
        ["Accent"]                   = Color.Parse("#F4A8C4"),
        ["AccentHover"]              = Color.Parse("#E891B2"),
        ["AccentPressed"]            = Color.Parse("#C57495"),
        ["AccentForeground"]         = Color.Parse("#1A0F14"),
        ["SystemAccentColor"]        = Color.Parse("#F4A8C4"),
        ["SystemAccentColorDark1"]   = Color.Parse("#E094B0"),
        ["SystemAccentColorDark2"]   = Color.Parse("#C57495"),
        ["SystemAccentColorDark3"]   = Color.Parse("#A85673"),
        ["SystemAccentColorLight1"]  = Color.Parse("#F6B7CF"),
        ["SystemAccentColorLight2"]  = Color.Parse("#F8C5DA"),
        ["SystemAccentColorLight3"]  = Color.Parse("#FAD4E4"),
        ["ThemeAccentColor"]         = Color.Parse("#F4A8C4"),
        ["ThemeAccentBrush3"]        = Color.Parse("#F6B7CF"),
        ["ThemeAccentBrush4"]        = Color.Parse("#F8C5DA"),
        ["SystemControlHighlightListAccentLowBrush"] = Color.Parse("#C57495"),
        ["TextPrimary"]              = Color.Parse("#F5EEF0"),
        ["TextSecondary"]            = Color.Parse("#9C7E87"),
        ["PlaceholderForeground"]    = Color.Parse("#A48891"),
        ["Success"]                  = Color.Parse("#4ADE80"),
        ["Error"]                    = Color.Parse("#F87171"),
        ["InputHoverSurface"]        = Color.Parse("#241A1D"),
        ["InputHoverBorder"]         = Color.Parse("#503843"),
        ["InputFocusSurface"]        = Color.Parse("#211A1D"),
        ["InputFocusBorder"]         = Color.Parse("#E891B2"),
        ["TableSurface"]             = Color.Parse("#1B1417"),
        ["TableRowBackground"]       = Color.Parse("#1B1417"),
        ["TableGap"]                 = Color.Parse("#161013"),
        ["TableHeaderBackground"]    = Color.Parse("#241A1E"),
        ["TableEmptyBackground"]     = Color.Parse("#1B1417"),
        ["TableRowDisabled"]         = Color.Parse("#1B1417"),
        ["SidebarItemForeground"]             = Color.Parse("#9C7E87"),
        ["SidebarItemHoverForeground"]        = Color.Parse("#F5EEF0"),
        ["SidebarItemHoverBackground"]        = Color.Parse("#251A1F"),
        ["SidebarItemSelectedForeground"]     = Color.Parse("#F5EEF0"),
        ["SidebarItemSelectedBackground"]     = Color.Parse("#2E2026"),
        ["ButtonSecondaryBackground"]         = Color.Parse("#00000000"),
        ["ButtonSecondaryForeground"]         = Color.Parse("#F5EEF0"),
        ["ButtonSecondaryBorder"]             = Color.Parse("#3A2A30"),
        ["ButtonSecondaryHoverBackground"]    = Color.Parse("#241A1D"),
        ["ButtonSecondaryHoverBorder"]        = Color.Parse("#503843"),
        ["ButtonSecondaryPressedBackground"]  = Color.Parse("#211A1D"),
        ["CheckboxBackground"]                = Color.Parse("#1F1719"),
        ["CheckboxBorder"]                    = Color.Parse("#9C7E87"),
        ["CheckboxHoverBackground"]           = Color.Parse("#241A1D"),
        ["CheckboxHoverBorder"]               = Color.Parse("#F4A8C4"),
        ["CheckboxCheckedBackground"]         = Color.Parse("#F4A8C4"),
        ["CheckboxCheckedBorder"]             = Color.Parse("#F4A8C4"),
        ["CheckboxCheckForeground"]           = Color.Parse("#1A0F14"),
        ["CheckboxLabelForeground"]           = Color.Parse("#F5EEF0"),
        ["CheckboxLabelHoverForeground"]      = Color.Parse("#F5EEF0"),
        ["RobloxBannerBackground"]            = Color.Parse("#291720"),
        ["ThemeCardHoverBackground"]          = Color.Parse("#241A1D"),
        ["ToggleHoverBackground"]             = Color.Parse("#241A1D"),
        ["ToggleHoverBorder"]                 = Color.Parse("#503843"),
        ["ToggleCheckedBackground"]           = Color.Parse("#2A1920"),
        ["ToggleCheckedBorder"]               = Color.Parse("#E891B2"),
        ["ShellBackground"]                   = Color.Parse("#1A1015"),
        ["ShellOuterBorder"]                  = Color.Parse("#F4A8C4"),
        ["ShellInnerBorder"]                  = Color.Parse("#E891B2"),
        ["ShellContentBackground"]            = Color.Parse("#21151A"),
        ["ShellContentBorder"]                = Color.Parse("#F4A8C4"),
        ["ShellNavBackground"]                = Color.Parse("#201419"),
        ["ShellNavHoverBackground"]           = Color.Parse("#302029"),
        ["ShellNavHoverBorder"]               = Color.Parse("#8A566B"),
        ["ShellNavSelectedBackground"]        = Color.Parse("#6A334C"),
        ["ShellNavSelectedBorder"]            = Color.Parse("#F4A8C4"),
        ["ShellNavGlow"]                      = Color.Parse("#E891B2"),
        ["ShellChromeBackground"]             = Color.Parse("#1B1116"),
        ["ShellChromeBorder"]                 = Color.Parse("#4A303A"),
        ["ShellShadow"]                       = Color.Parse("#40000000"),
        ["ShellSelectedShadow"]               = Color.Parse("#60000000"),
    };

    public static IReadOnlyDictionary<string, Color> Slate { get; } = new Dictionary<string, Color>
    {
        ["Background"]               = Color.Parse("#0F1520"),
        ["Surface"]                  = Color.Parse("#151D2B"),
        ["Border"]                   = Color.Parse("#2B3A52"),
        ["Accent"]                   = Color.Parse("#7FB6FF"),
        ["AccentHover"]              = Color.Parse("#69A8FA"),
        ["AccentPressed"]            = Color.Parse("#4C8EDB"),
        ["AccentForeground"]         = Color.Parse("#0B1114"),
        ["SystemAccentColor"]        = Color.Parse("#7FB6FF"),
        ["SystemAccentColorDark1"]   = Color.Parse("#6AA4F2"),
        ["SystemAccentColorDark2"]   = Color.Parse("#4C8EDB"),
        ["SystemAccentColorDark3"]   = Color.Parse("#3577C2"),
        ["SystemAccentColorLight1"]  = Color.Parse("#96C4FF"),
        ["SystemAccentColorLight2"]  = Color.Parse("#ADD2FF"),
        ["SystemAccentColorLight3"]  = Color.Parse("#C4E0FF"),
        ["ThemeAccentColor"]         = Color.Parse("#7FB6FF"),
        ["ThemeAccentBrush3"]        = Color.Parse("#96C4FF"),
        ["ThemeAccentBrush4"]        = Color.Parse("#ADD2FF"),
        ["SystemControlHighlightListAccentLowBrush"] = Color.Parse("#4C8EDB"),
        ["TextPrimary"]              = Color.Parse("#EEF4FF"),
        ["TextSecondary"]            = Color.Parse("#8FA1BF"),
        ["PlaceholderForeground"]    = Color.Parse("#97A7C2"),
        ["Success"]                  = Color.Parse("#46C981"),
        ["Error"]                    = Color.Parse("#EF767A"),
        ["InputHoverSurface"]        = Color.Parse("#1B2637"),
        ["InputHoverBorder"]         = Color.Parse("#3F5474"),
        ["InputFocusSurface"]        = Color.Parse("#172131"),
        ["InputFocusBorder"]         = Color.Parse("#69A8FA"),
        ["TableSurface"]             = Color.Parse("#131A27"),
        ["TableRowBackground"]       = Color.Parse("#131A27"),
        ["TableGap"]                 = Color.Parse("#0C1220"),
        ["TableHeaderBackground"]    = Color.Parse("#1A2333"),
        ["TableEmptyBackground"]     = Color.Parse("#131A27"),
        ["TableRowDisabled"]         = Color.Parse("#151D2A"),
        ["SidebarItemForeground"]             = Color.Parse("#8FA1BF"),
        ["SidebarItemHoverForeground"]        = Color.Parse("#EEF4FF"),
        ["SidebarItemHoverBackground"]        = Color.Parse("#1D283A"),
        ["SidebarItemSelectedForeground"]     = Color.Parse("#F3F7FF"),
        ["SidebarItemSelectedBackground"]     = Color.Parse("#203B63"),
        ["ButtonSecondaryBackground"]         = Color.Parse("#00000000"),
        ["ButtonSecondaryForeground"]         = Color.Parse("#EEF4FF"),
        ["ButtonSecondaryBorder"]             = Color.Parse("#2B3A52"),
        ["ButtonSecondaryHoverBackground"]    = Color.Parse("#1B2637"),
        ["ButtonSecondaryHoverBorder"]        = Color.Parse("#3F5474"),
        ["ButtonSecondaryPressedBackground"]  = Color.Parse("#223149"),
        ["CheckboxBackground"]                = Color.Parse("#131B28"),
        ["CheckboxBorder"]                    = Color.Parse("#59739B"),
        ["CheckboxHoverBackground"]           = Color.Parse("#1B2637"),
        ["CheckboxHoverBorder"]               = Color.Parse("#7FB6FF"),
        ["CheckboxCheckedBackground"]         = Color.Parse("#7FB6FF"),
        ["CheckboxCheckedBorder"]             = Color.Parse("#7FB6FF"),
        ["CheckboxCheckForeground"]           = Color.Parse("#0B1114"),
        ["CheckboxLabelForeground"]           = Color.Parse("#EEF4FF"),
        ["CheckboxLabelHoverForeground"]      = Color.Parse("#EEF4FF"),
        ["RobloxBannerBackground"]            = Color.Parse("#13233A"),
        ["ThemeCardHoverBackground"]          = Color.Parse("#1B2637"),
        ["ToggleHoverBackground"]             = Color.Parse("#1B2637"),
        ["ToggleHoverBorder"]                 = Color.Parse("#3F5474"),
        ["ToggleCheckedBackground"]           = Color.Parse("#1A3154"),
        ["ToggleCheckedBorder"]               = Color.Parse("#4C8EDB"),
        ["ShellBackground"]                   = Color.Parse("#0D1624"),
        ["ShellOuterBorder"]                  = Color.Parse("#7FB6FF"),
        ["ShellInnerBorder"]                  = Color.Parse("#69A8FA"),
        ["ShellContentBackground"]            = Color.Parse("#121A28"),
        ["ShellContentBorder"]                = Color.Parse("#7FB6FF"),
        ["ShellNavBackground"]                = Color.Parse("#121A28"),
        ["ShellNavHoverBackground"]           = Color.Parse("#1A2740"),
        ["ShellNavHoverBorder"]               = Color.Parse("#48658A"),
        ["ShellNavSelectedBackground"]        = Color.Parse("#214271"),
        ["ShellNavSelectedBorder"]            = Color.Parse("#7FB6FF"),
        ["ShellNavGlow"]                      = Color.Parse("#69A8FA"),
        ["ShellChromeBackground"]             = Color.Parse("#111826"),
        ["ShellChromeBorder"]                 = Color.Parse("#2B3A52"),
        ["ShellShadow"]                       = Color.Parse("#40000000"),
        ["ShellSelectedShadow"]               = Color.Parse("#60000000"),
    };
}
