using System;
using System.Collections.Generic;
using Avalonia.Media;

namespace Client.Services;

public static class ThemeColors
{
    public static IReadOnlyDictionary<string, Color> BuildCustom(CustomThemeAnchors anchors)
    {
        var bg = anchors.Background;
        var surf = anchors.Surface;
        var border = anchors.Border;
        var accent = anchors.Accent;
        var text = anchors.TextPrimary;

        var isDark = RelativeLuminance(bg) < 0.5;

        var textSecondary = Lerp(text, bg, 0.55);
        var accentHover = Lerp(accent, bg, 0.18);
        var accentPressed = Lerp(accent, bg, 0.36);
        var accentForeground = RelativeLuminance(accent) > 0.55 ? bg : Color.FromRgb(0xFF, 0xFF, 0xFF);

        var inputHoverSurface = Lerp(surf, border, 0.35);
        var inputHoverBorder = Lerp(border, text, 0.25);
        var inputFocusSurface = Lerp(surf, bg, 0.5);
        var inputFocusBorder = accentHover;

        var tableSurface = Lerp(surf, bg, 0.4);
        var tableHeaderBackground = Lerp(surf, border, 0.2);

        var sidebarHoverBackground = Lerp(bg, border, 0.35);
        var sidebarSelectedBackground = Lerp(bg, border, 0.6);

        var updateBannerBackground = Lerp(bg, accent, 0.18);

        return new Dictionary<string, Color>
        {
            ["Background"]               = bg,
            ["Surface"]                  = surf,
            ["Border"]                   = border,
            ["Accent"]                   = accent,
            ["AccentHover"]              = accentHover,
            ["AccentPressed"]            = accentPressed,
            ["AccentForeground"]         = accentForeground,
            ["TextPrimary"]              = text,
            ["TextSecondary"]            = textSecondary,
            ["Success"]                  = isDark ? Color.Parse("#4ADE80") : Color.Parse("#15803D"),
            ["Error"]                    = isDark ? Color.Parse("#F87171") : Color.Parse("#DC2626"),
            ["InputHoverSurface"]        = inputHoverSurface,
            ["InputHoverBorder"]         = inputHoverBorder,
            ["InputFocusSurface"]        = inputFocusSurface,
            ["InputFocusBorder"]         = inputFocusBorder,
            ["TableSurface"]             = tableSurface,
            ["TableRowBackground"]       = tableSurface,
            ["TableGap"]                 = bg,
            ["TableHeaderBackground"]    = tableHeaderBackground,
            ["TableEmptyBackground"]     = tableSurface,
            ["TableRowDisabled"]         = tableSurface,
            ["SidebarItemForeground"]             = textSecondary,
            ["SidebarItemHoverForeground"]        = text,
            ["SidebarItemHoverBackground"]        = sidebarHoverBackground,
            ["SidebarItemSelectedForeground"]     = text,
            ["SidebarItemSelectedBackground"]     = sidebarSelectedBackground,
            ["ButtonSecondaryBackground"]         = Color.FromArgb(0, 0, 0, 0),
            ["ButtonSecondaryForeground"]         = text,
            ["ButtonSecondaryBorder"]             = border,
            ["ButtonSecondaryHoverBackground"]    = inputHoverSurface,
            ["ButtonSecondaryHoverBorder"]        = inputHoverBorder,
            ["ButtonSecondaryPressedBackground"]  = inputFocusSurface,
            ["CheckboxBackground"]                = surf,
            ["CheckboxBorder"]                    = textSecondary,
            ["CheckboxHoverBackground"]           = inputHoverSurface,
            ["CheckboxHoverBorder"]               = accent,
            ["CheckboxCheckedBackground"]         = accent,
            ["CheckboxCheckedBorder"]             = accent,
            ["CheckboxCheckForeground"]           = accentForeground,
            ["CheckboxLabelForeground"]           = text,
            ["CheckboxLabelHoverForeground"]      = text,
            ["RobloxBannerBackground"]            = updateBannerBackground,
            ["ThemeCardHoverBackground"]          = inputHoverSurface,
            ["ToggleHoverBackground"]             = inputHoverSurface,
            ["ToggleHoverBorder"]                 = inputHoverBorder,
            ["ToggleCheckedBackground"]           = sidebarSelectedBackground,
            ["ToggleCheckedBorder"]               = accentPressed,
            ["ShellBackground"]                   = bg,
            ["ShellOuterBorder"]                  = Lerp(border, bg, isDark ? 0.65 : 0.15),
            ["ShellInnerBorder"]                  = border,
            ["ShellContentBackground"]            = tableSurface,
            ["ShellContentBorder"]                = border,
            ["ShellNavBackground"]                = surf,
            ["ShellNavHoverBackground"]           = sidebarHoverBackground,
            ["ShellNavHoverBorder"]               = inputHoverBorder,
            ["ShellNavSelectedBackground"]        = sidebarSelectedBackground,
            ["ShellNavSelectedBorder"]            = accent,
            ["ShellNavGlow"]                      = accent,
            ["ShellChromeBackground"]             = tableSurface,
            ["ShellChromeBorder"]                 = border,
        };
    }

    private static Color Lerp(Color a, Color b, double t)
    {
        t = Math.Clamp(t, 0.0, 1.0);
        return Color.FromArgb(
            (byte)Math.Round(a.A + (b.A - a.A) * t),
            (byte)Math.Round(a.R + (b.R - a.R) * t),
            (byte)Math.Round(a.G + (b.G - a.G) * t),
            (byte)Math.Round(a.B + (b.B - a.B) * t));
    }

    private static double RelativeLuminance(Color c)
        => (0.2126 * c.R + 0.7152 * c.G + 0.0722 * c.B) / 255.0;


    public static IReadOnlyDictionary<string, Color> Dark { get; } = new Dictionary<string, Color>
    {
        ["Background"]               = Color.Parse("#08090B"),
        ["Surface"]                  = Color.Parse("#131519"),
        ["Border"]                   = Color.Parse("#5F646C"),
        ["Accent"]                   = Color.Parse("#E7E9EC"),
        ["AccentHover"]              = Color.Parse("#FFFFFF"),
        ["AccentPressed"]            = Color.Parse("#BFC3C9"),
        ["AccentForeground"]         = Color.Parse("#090A0C"),
        ["TextPrimary"]              = Color.Parse("#F5F5F6"),
        ["TextSecondary"]            = Color.Parse("#A7AAB0"),
        ["Success"]                  = Color.Parse("#4ADE80"),
        ["Error"]                    = Color.Parse("#F87171"),
        ["InputHoverSurface"]        = Color.Parse("#202329"),
        ["InputHoverBorder"]         = Color.Parse("#8D929A"),
        ["InputFocusSurface"]        = Color.Parse("#181B20"),
        ["InputFocusBorder"]         = Color.Parse("#F1F2F4"),
        ["TableSurface"]             = Color.Parse("#101216"),
        ["TableRowBackground"]       = Color.Parse("#101216"),
        ["TableGap"]                 = Color.Parse("#08090B"),
        ["TableHeaderBackground"]    = Color.Parse("#1A1D22"),
        ["TableEmptyBackground"]     = Color.Parse("#101216"),
        ["TableRowDisabled"]         = Color.Parse("#101216"),
        ["SidebarItemForeground"]             = Color.Parse("#A7AAB0"),
        ["SidebarItemHoverForeground"]        = Color.Parse("#F5F5F6"),
        ["SidebarItemHoverBackground"]        = Color.Parse("#202329"),
        ["SidebarItemSelectedForeground"]     = Color.Parse("#FFFFFF"),
        ["SidebarItemSelectedBackground"]     = Color.Parse("#4B4F56"),
        ["ButtonSecondaryBackground"]         = Color.Parse("#00000000"),
        ["ButtonSecondaryForeground"]         = Color.Parse("#E7E9EC"),
        ["ButtonSecondaryBorder"]             = Color.Parse("#777C84"),
        ["ButtonSecondaryHoverBackground"]    = Color.Parse("#202329"),
        ["ButtonSecondaryHoverBorder"]        = Color.Parse("#F1F2F4"),
        ["ButtonSecondaryPressedBackground"]  = Color.Parse("#191C21"),
        ["CheckboxBackground"]                = Color.Parse("#131519"),
        ["CheckboxBorder"]                    = Color.Parse("#92969D"),
        ["CheckboxHoverBackground"]           = Color.Parse("#202329"),
        ["CheckboxHoverBorder"]               = Color.Parse("#F1F2F4"),
        ["CheckboxCheckedBackground"]         = Color.Parse("#F1F2F4"),
        ["CheckboxCheckedBorder"]             = Color.Parse("#F1F2F4"),
        ["CheckboxCheckForeground"]           = Color.Parse("#090A0C"),
        ["CheckboxLabelForeground"]           = Color.Parse("#F5F5F6"),
        ["CheckboxLabelHoverForeground"]      = Color.Parse("#F5F5F6"),
        ["RobloxBannerBackground"]            = Color.Parse("#131519"),
        ["ThemeCardHoverBackground"]          = Color.Parse("#202329"),
        ["ToggleHoverBackground"]             = Color.Parse("#202329"),
        ["ToggleHoverBorder"]                 = Color.Parse("#777C84"),
        ["ToggleCheckedBackground"]           = Color.Parse("#30343A"),
        ["ToggleCheckedBorder"]               = Color.Parse("#C6C9CE"),
        ["ShellBackground"]                   = Color.Parse("#0C1016"),
        ["ShellOuterBorder"]                  = Color.Parse("#05070A"),
        ["ShellInnerBorder"]                  = Color.Parse("#7B8797"),
        ["ShellContentBackground"]            = Color.Parse("#090D13"),
        ["ShellContentBorder"]                = Color.Parse("#394555"),
        ["ShellNavBackground"]                = Color.Parse("#0B1017"),
        ["ShellNavHoverBackground"]           = Color.Parse("#151B23"),
        ["ShellNavHoverBorder"]               = Color.Parse("#6D7581"),
        ["ShellNavSelectedBackground"]        = Color.Parse("#283341"),
        ["ShellNavSelectedBorder"]            = Color.Parse("#F5F8FC"),
        ["ShellNavGlow"]                      = Color.Parse("#D8E3F0"),
        ["ShellChromeBackground"]             = Color.Parse("#0D0F12"),
        ["ShellChromeBorder"]                 = Color.Parse("#373B42"),
    };

    public static IReadOnlyDictionary<string, Color> Light { get; } = new Dictionary<string, Color>
    {
        ["Background"]               = Color.Parse("#F7F8F8"),
        ["Surface"]                  = Color.Parse("#FFFFFF"),
        ["Border"]                   = Color.Parse("#D8DEDC"),
        ["Accent"]                   = Color.Parse("#7D8588"),
        ["AccentHover"]              = Color.Parse("#687174"),
        ["AccentPressed"]            = Color.Parse("#555D60"),
        ["AccentForeground"]         = Color.Parse("#FFFFFF"),
        ["TextPrimary"]              = Color.Parse("#171717"),
        ["TextSecondary"]            = Color.Parse("#66706D"),
        ["Success"]                  = Color.Parse("#15803D"),
        ["Error"]                    = Color.Parse("#DC2626"),
        ["InputHoverSurface"]        = Color.Parse("#F1F4F3"),
        ["InputHoverBorder"]         = Color.Parse("#C8D1CE"),
        ["InputFocusSurface"]        = Color.Parse("#FFFFFF"),
        ["InputFocusBorder"]         = Color.Parse("#7D8588"),
        ["TableSurface"]             = Color.Parse("#FFFFFF"),
        ["TableRowBackground"]       = Color.Parse("#FFFFFF"),
        ["TableGap"]                 = Color.Parse("#EEF1F0"),
        ["TableHeaderBackground"]    = Color.Parse("#F1F4F3"),
        ["TableEmptyBackground"]     = Color.Parse("#FFFFFF"),
        ["TableRowDisabled"]         = Color.Parse("#F6F7F7"),
        ["SidebarItemForeground"]             = Color.Parse("#66706D"),
        ["SidebarItemHoverForeground"]        = Color.Parse("#171717"),
        ["SidebarItemHoverBackground"]        = Color.Parse("#E6EDEC"),
        ["SidebarItemSelectedForeground"]     = Color.Parse("#171717"),
        ["SidebarItemSelectedBackground"]     = Color.Parse("#DDE1E2"),
        ["ButtonSecondaryBackground"]         = Color.Parse("#00000000"),
        ["ButtonSecondaryForeground"]         = Color.Parse("#171717"),
        ["ButtonSecondaryBorder"]             = Color.Parse("#D8DEDC"),
        ["ButtonSecondaryHoverBackground"]    = Color.Parse("#F1F4F3"),
        ["ButtonSecondaryHoverBorder"]        = Color.Parse("#C8D1CE"),
        ["ButtonSecondaryPressedBackground"]  = Color.Parse("#E6EDEC"),
        ["CheckboxBackground"]                = Color.Parse("#FFFFFF"),
        ["CheckboxBorder"]                    = Color.Parse("#8D9996"),
        ["CheckboxHoverBackground"]           = Color.Parse("#F1F4F3"),
        ["CheckboxHoverBorder"]               = Color.Parse("#7D8588"),
        ["CheckboxCheckedBackground"]         = Color.Parse("#7D8588"),
        ["CheckboxCheckedBorder"]             = Color.Parse("#7D8588"),
        ["CheckboxCheckForeground"]           = Color.Parse("#FFFFFF"),
        ["CheckboxLabelForeground"]           = Color.Parse("#171717"),
        ["CheckboxLabelHoverForeground"]      = Color.Parse("#171717"),
        ["RobloxBannerBackground"]            = Color.Parse("#EAF3F2"),
        ["ThemeCardHoverBackground"]          = Color.Parse("#F1F4F3"),
        ["ToggleHoverBackground"]             = Color.Parse("#EEF4F6"),
        ["ToggleHoverBorder"]                 = Color.Parse("#C8D1CE"),
        ["ToggleCheckedBackground"]           = Color.Parse("#DDE1E2"),
        ["ToggleCheckedBorder"]               = Color.Parse("#7D8588"),
        ["ShellBackground"]                   = Color.Parse("#EEF3F2"),
        ["ShellOuterBorder"]                  = Color.Parse("#AEBAB7"),
        ["ShellInnerBorder"]                  = Color.Parse("#FFFFFF"),
        ["ShellContentBackground"]            = Color.Parse("#FFFFFF"),
        ["ShellContentBorder"]                = Color.Parse("#CBD5D2"),
        ["ShellNavBackground"]                = Color.Parse("#F8FAF9"),
        ["ShellNavHoverBackground"]           = Color.Parse("#E7EFED"),
        ["ShellNavHoverBorder"]               = Color.Parse("#9DB2AE"),
        ["ShellNavSelectedBackground"]        = Color.Parse("#DDE1E2"),
        ["ShellNavSelectedBorder"]            = Color.Parse("#7D8588"),
        ["ShellNavGlow"]                      = Color.Parse("#AAB0B2"),
        ["ShellChromeBackground"]             = Color.Parse("#F7F9F8"),
        ["ShellChromeBorder"]                 = Color.Parse("#CBD5D2"),
    };

    // Soft-pink dark palette. Keeps the same readable dark base as Dark/Slate;
    // accents and selection/hover tints are pink instead of teal.
    public static IReadOnlyDictionary<string, Color> Pink { get; } = new Dictionary<string, Color>
    {
        ["Background"]               = Color.Parse("#161013"),
        ["Surface"]                  = Color.Parse("#1F1719"),
        ["Border"]                   = Color.Parse("#3A2A30"),
        ["Accent"]                   = Color.Parse("#F4A8C4"),
        ["AccentHover"]              = Color.Parse("#E891B2"),
        ["AccentPressed"]            = Color.Parse("#C57495"),
        ["AccentForeground"]         = Color.Parse("#1A0F14"),
        ["TextPrimary"]              = Color.Parse("#F5EEF0"),
        ["TextSecondary"]            = Color.Parse("#9C7E87"),
        ["Success"]                  = Color.Parse("#4ADE80"),
        ["Error"]                    = Color.Parse("#F87171"),
        ["InputHoverSurface"]        = Color.Parse("#241A1D"),
        ["InputHoverBorder"]         = Color.Parse("#503843"),
        ["InputFocusSurface"]        = Color.Parse("#211A1D"),
        ["InputFocusBorder"]         = Color.Parse("#E891B2"),
        ["TableSurface"]             = Color.Parse("#1B1417"),
        ["TableRowBackground"]       = Color.Parse("#1B1417"),
        ["TableGap"]                 = Color.Parse("#161013"),
        ["TableHeaderBackground"]    = Color.Parse("#241A1E"),
        ["TableEmptyBackground"]     = Color.Parse("#1B1417"),
        ["TableRowDisabled"]         = Color.Parse("#1B1417"),
        ["SidebarItemForeground"]             = Color.Parse("#9C7E87"),
        ["SidebarItemHoverForeground"]        = Color.Parse("#F5EEF0"),
        ["SidebarItemHoverBackground"]        = Color.Parse("#251A1F"),
        ["SidebarItemSelectedForeground"]     = Color.Parse("#F5EEF0"),
        ["SidebarItemSelectedBackground"]     = Color.Parse("#2E2026"),
        ["ButtonSecondaryBackground"]         = Color.Parse("#00000000"),
        ["ButtonSecondaryForeground"]         = Color.Parse("#F5EEF0"),
        ["ButtonSecondaryBorder"]             = Color.Parse("#3A2A30"),
        ["ButtonSecondaryHoverBackground"]    = Color.Parse("#241A1D"),
        ["ButtonSecondaryHoverBorder"]        = Color.Parse("#503843"),
        ["ButtonSecondaryPressedBackground"]  = Color.Parse("#211A1D"),
        ["CheckboxBackground"]                = Color.Parse("#1F1719"),
        ["CheckboxBorder"]                    = Color.Parse("#9C7E87"),
        ["CheckboxHoverBackground"]           = Color.Parse("#241A1D"),
        ["CheckboxHoverBorder"]               = Color.Parse("#F4A8C4"),
        ["CheckboxCheckedBackground"]         = Color.Parse("#F4A8C4"),
        ["CheckboxCheckedBorder"]             = Color.Parse("#F4A8C4"),
        ["CheckboxCheckForeground"]           = Color.Parse("#1A0F14"),
        ["CheckboxLabelForeground"]           = Color.Parse("#F5EEF0"),
        ["CheckboxLabelHoverForeground"]      = Color.Parse("#F5EEF0"),
        ["RobloxBannerBackground"]            = Color.Parse("#291720"),
        ["ThemeCardHoverBackground"]          = Color.Parse("#241A1D"),
        ["ToggleHoverBackground"]             = Color.Parse("#241A1D"),
        ["ToggleHoverBorder"]                 = Color.Parse("#503843"),
        ["ToggleCheckedBackground"]           = Color.Parse("#2A1920"),
        ["ToggleCheckedBorder"]               = Color.Parse("#E891B2"),
        ["ShellBackground"]                   = Color.Parse("#1A1015"),
        ["ShellOuterBorder"]                  = Color.Parse("#090508"),
        ["ShellInnerBorder"]                  = Color.Parse("#6F4354"),
        ["ShellContentBackground"]            = Color.Parse("#21151A"),
        ["ShellContentBorder"]                = Color.Parse("#4A303A"),
        ["ShellNavBackground"]                = Color.Parse("#201419"),
        ["ShellNavHoverBackground"]           = Color.Parse("#302029"),
        ["ShellNavHoverBorder"]               = Color.Parse("#8A566B"),
        ["ShellNavSelectedBackground"]        = Color.Parse("#6A334C"),
        ["ShellNavSelectedBorder"]            = Color.Parse("#F4A8C4"),
        ["ShellNavGlow"]                      = Color.Parse("#E891B2"),
        ["ShellChromeBackground"]             = Color.Parse("#1B1116"),
        ["ShellChromeBorder"]                 = Color.Parse("#4A303A"),
    };

    public static IReadOnlyDictionary<string, Color> Slate { get; } = new Dictionary<string, Color>
    {
        ["Background"]               = Color.Parse("#0F1520"),
        ["Surface"]                  = Color.Parse("#151D2B"),
        ["Border"]                   = Color.Parse("#2B3A52"),
        ["Accent"]                   = Color.Parse("#7FB6FF"),
        ["AccentHover"]              = Color.Parse("#69A8FA"),
        ["AccentPressed"]            = Color.Parse("#4C8EDB"),
        ["AccentForeground"]         = Color.Parse("#0B1114"),
        ["TextPrimary"]              = Color.Parse("#EEF4FF"),
        ["TextSecondary"]            = Color.Parse("#8FA1BF"),
        ["Success"]                  = Color.Parse("#46C981"),
        ["Error"]                    = Color.Parse("#EF767A"),
        ["InputHoverSurface"]        = Color.Parse("#1B2637"),
        ["InputHoverBorder"]         = Color.Parse("#3F5474"),
        ["InputFocusSurface"]        = Color.Parse("#172131"),
        ["InputFocusBorder"]         = Color.Parse("#69A8FA"),
        ["TableSurface"]             = Color.Parse("#131A27"),
        ["TableRowBackground"]       = Color.Parse("#131A27"),
        ["TableGap"]                 = Color.Parse("#0C1220"),
        ["TableHeaderBackground"]    = Color.Parse("#1A2333"),
        ["TableEmptyBackground"]     = Color.Parse("#131A27"),
        ["TableRowDisabled"]         = Color.Parse("#151D2A"),
        ["SidebarItemForeground"]             = Color.Parse("#8FA1BF"),
        ["SidebarItemHoverForeground"]        = Color.Parse("#EEF4FF"),
        ["SidebarItemHoverBackground"]        = Color.Parse("#1D283A"),
        ["SidebarItemSelectedForeground"]     = Color.Parse("#F3F7FF"),
        ["SidebarItemSelectedBackground"]     = Color.Parse("#203B63"),
        ["ButtonSecondaryBackground"]         = Color.Parse("#00000000"),
        ["ButtonSecondaryForeground"]         = Color.Parse("#EEF4FF"),
        ["ButtonSecondaryBorder"]             = Color.Parse("#2B3A52"),
        ["ButtonSecondaryHoverBackground"]    = Color.Parse("#1B2637"),
        ["ButtonSecondaryHoverBorder"]        = Color.Parse("#3F5474"),
        ["ButtonSecondaryPressedBackground"]  = Color.Parse("#223149"),
        ["CheckboxBackground"]                = Color.Parse("#131B28"),
        ["CheckboxBorder"]                    = Color.Parse("#59739B"),
        ["CheckboxHoverBackground"]           = Color.Parse("#1B2637"),
        ["CheckboxHoverBorder"]               = Color.Parse("#7FB6FF"),
        ["CheckboxCheckedBackground"]         = Color.Parse("#7FB6FF"),
        ["CheckboxCheckedBorder"]             = Color.Parse("#7FB6FF"),
        ["CheckboxCheckForeground"]           = Color.Parse("#0B1114"),
        ["CheckboxLabelForeground"]           = Color.Parse("#EEF4FF"),
        ["CheckboxLabelHoverForeground"]      = Color.Parse("#EEF4FF"),
        ["RobloxBannerBackground"]            = Color.Parse("#13233A"),
        ["ThemeCardHoverBackground"]          = Color.Parse("#1B2637"),
        ["ToggleHoverBackground"]             = Color.Parse("#1B2637"),
        ["ToggleHoverBorder"]                 = Color.Parse("#3F5474"),
        ["ToggleCheckedBackground"]           = Color.Parse("#1A3154"),
        ["ToggleCheckedBorder"]               = Color.Parse("#4C8EDB"),
        ["ShellBackground"]                   = Color.Parse("#0D1624"),
        ["ShellOuterBorder"]                  = Color.Parse("#070A0C"),
        ["ShellInnerBorder"]                  = Color.Parse("#456086"),
        ["ShellContentBackground"]            = Color.Parse("#121A28"),
        ["ShellContentBorder"]                = Color.Parse("#2B3A52"),
        ["ShellNavBackground"]                = Color.Parse("#121A28"),
        ["ShellNavHoverBackground"]           = Color.Parse("#1A2740"),
        ["ShellNavHoverBorder"]               = Color.Parse("#48658A"),
        ["ShellNavSelectedBackground"]        = Color.Parse("#214271"),
        ["ShellNavSelectedBorder"]            = Color.Parse("#7FB6FF"),
        ["ShellNavGlow"]                      = Color.Parse("#69A8FA"),
        ["ShellChromeBackground"]             = Color.Parse("#111826"),
        ["ShellChromeBorder"]                 = Color.Parse("#2B3A52"),
    };
}
